// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// XaddressesColumns holds the columns for the "xaddresses" table.
	XaddressesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "default", Type: field.TypeInt64},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "country_id", Type: field.TypeInt64},
		{Name: "street", Type: field.TypeString},
		{Name: "province", Type: field.TypeString},
		{Name: "city", Type: field.TypeString},
		{Name: "postal_code", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
	}
	// XaddressesTable holds the schema information for the "xaddresses" table.
	XaddressesTable = &schema.Table{
		Name:       "xaddresses",
		Columns:    XaddressesColumns,
		PrimaryKey: []*schema.Column{XaddressesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		XaddressesTable,
	}
)

func init() {
}
