// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/yumo001/simple-learn-rpc/ent/xaddress"
)

const errInvalidPage = "INVALID_PAGE"

const (
	listField     = "list"
	pageNumField  = "pageNum"
	pageSizeField = "pageSize"
)

type PageDetails struct {
	Page  uint64 `json:"page"`
	Size  uint64 `json:"size"`
	Total uint64 `json:"total"`
}

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

const errInvalidPagination = "INVALID_PAGINATION"

type XAddressPager struct {
	Order  xaddress.OrderOption
	Filter func(*XAddressQuery) (*XAddressQuery, error)
}

// XAddressPaginateOption enables pagination customization.
type XAddressPaginateOption func(*XAddressPager)

// DefaultXAddressOrder is the default ordering of XAddress.
var DefaultXAddressOrder = Desc(xaddress.FieldID)

func newXAddressPager(opts []XAddressPaginateOption) (*XAddressPager, error) {
	pager := &XAddressPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultXAddressOrder
	}
	return pager, nil
}

func (p *XAddressPager) ApplyFilter(query *XAddressQuery) (*XAddressQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// XAddressPageList is XAddress PageList result.
type XAddressPageList struct {
	List        []*XAddress  `json:"list"`
	PageDetails *PageDetails `json:"pageDetails"`
}

func (x *XAddressQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...XAddressPaginateOption,
) (*XAddressPageList, error) {

	pager, err := newXAddressPager(opts)
	if err != nil {
		return nil, err
	}

	if x, err = pager.ApplyFilter(x); err != nil {
		return nil, err
	}

	ret := &XAddressPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := x.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		x = x.Order(pager.Order)
	} else {
		x = x.Order(DefaultXAddressOrder)
	}

	x = x.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := x.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}
