// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (x *XAddressUpdate) SetNotNilUpdatedAt(value *time.Time) *XAddressUpdate {
	if value != nil {
		return x.SetUpdatedAt(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdateOne) SetNotNilUpdatedAt(value *time.Time) *XAddressUpdateOne {
	if value != nil {
		return x.SetUpdatedAt(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressCreate) SetNotNilUpdatedAt(value *time.Time) *XAddressCreate {
	if value != nil {
		return x.SetUpdatedAt(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdate) SetNotNilUserID(value *int64) *XAddressUpdate {
	if value != nil {
		return x.SetUserID(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdateOne) SetNotNilUserID(value *int64) *XAddressUpdateOne {
	if value != nil {
		return x.SetUserID(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressCreate) SetNotNilUserID(value *int64) *XAddressCreate {
	if value != nil {
		return x.SetUserID(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdate) SetNotNilDefault(value *int64) *XAddressUpdate {
	if value != nil {
		return x.SetDefault(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdateOne) SetNotNilDefault(value *int64) *XAddressUpdateOne {
	if value != nil {
		return x.SetDefault(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressCreate) SetNotNilDefault(value *int64) *XAddressCreate {
	if value != nil {
		return x.SetDefault(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdate) SetNotNilFirstName(value *string) *XAddressUpdate {
	if value != nil {
		return x.SetFirstName(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdateOne) SetNotNilFirstName(value *string) *XAddressUpdateOne {
	if value != nil {
		return x.SetFirstName(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressCreate) SetNotNilFirstName(value *string) *XAddressCreate {
	if value != nil {
		return x.SetFirstName(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdate) SetNotNilLastName(value *string) *XAddressUpdate {
	if value != nil {
		return x.SetLastName(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdateOne) SetNotNilLastName(value *string) *XAddressUpdateOne {
	if value != nil {
		return x.SetLastName(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressCreate) SetNotNilLastName(value *string) *XAddressCreate {
	if value != nil {
		return x.SetLastName(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdate) SetNotNilCountryID(value *int64) *XAddressUpdate {
	if value != nil {
		return x.SetCountryID(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdateOne) SetNotNilCountryID(value *int64) *XAddressUpdateOne {
	if value != nil {
		return x.SetCountryID(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressCreate) SetNotNilCountryID(value *int64) *XAddressCreate {
	if value != nil {
		return x.SetCountryID(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdate) SetNotNilStreet(value *string) *XAddressUpdate {
	if value != nil {
		return x.SetStreet(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdateOne) SetNotNilStreet(value *string) *XAddressUpdateOne {
	if value != nil {
		return x.SetStreet(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressCreate) SetNotNilStreet(value *string) *XAddressCreate {
	if value != nil {
		return x.SetStreet(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdate) SetNotNilProvince(value *string) *XAddressUpdate {
	if value != nil {
		return x.SetProvince(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdateOne) SetNotNilProvince(value *string) *XAddressUpdateOne {
	if value != nil {
		return x.SetProvince(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressCreate) SetNotNilProvince(value *string) *XAddressCreate {
	if value != nil {
		return x.SetProvince(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdate) SetNotNilCity(value *string) *XAddressUpdate {
	if value != nil {
		return x.SetCity(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdateOne) SetNotNilCity(value *string) *XAddressUpdateOne {
	if value != nil {
		return x.SetCity(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressCreate) SetNotNilCity(value *string) *XAddressCreate {
	if value != nil {
		return x.SetCity(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdate) SetNotNilPostalCode(value *string) *XAddressUpdate {
	if value != nil {
		return x.SetPostalCode(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdateOne) SetNotNilPostalCode(value *string) *XAddressUpdateOne {
	if value != nil {
		return x.SetPostalCode(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressCreate) SetNotNilPostalCode(value *string) *XAddressCreate {
	if value != nil {
		return x.SetPostalCode(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdate) SetNotNilPhone(value *string) *XAddressUpdate {
	if value != nil {
		return x.SetPhone(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressUpdateOne) SetNotNilPhone(value *string) *XAddressUpdateOne {
	if value != nil {
		return x.SetPhone(*value)
	}
	return x
}

// set field if value's pointer is not nil.
func (x *XAddressCreate) SetNotNilPhone(value *string) *XAddressCreate {
	if value != nil {
		return x.SetPhone(*value)
	}
	return x
}
