// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yumo001/simple-learn-rpc/ent/predicate"
	"github.com/yumo001/simple-learn-rpc/ent/xaddress"
)

// XAddressQuery is the builder for querying XAddress entities.
type XAddressQuery struct {
	config
	ctx        *QueryContext
	order      []xaddress.OrderOption
	inters     []Interceptor
	predicates []predicate.XAddress
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the XAddressQuery builder.
func (xq *XAddressQuery) Where(ps ...predicate.XAddress) *XAddressQuery {
	xq.predicates = append(xq.predicates, ps...)
	return xq
}

// Limit the number of records to be returned by this query.
func (xq *XAddressQuery) Limit(limit int) *XAddressQuery {
	xq.ctx.Limit = &limit
	return xq
}

// Offset to start from.
func (xq *XAddressQuery) Offset(offset int) *XAddressQuery {
	xq.ctx.Offset = &offset
	return xq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (xq *XAddressQuery) Unique(unique bool) *XAddressQuery {
	xq.ctx.Unique = &unique
	return xq
}

// Order specifies how the records should be ordered.
func (xq *XAddressQuery) Order(o ...xaddress.OrderOption) *XAddressQuery {
	xq.order = append(xq.order, o...)
	return xq
}

// First returns the first XAddress entity from the query.
// Returns a *NotFoundError when no XAddress was found.
func (xq *XAddressQuery) First(ctx context.Context) (*XAddress, error) {
	nodes, err := xq.Limit(1).All(setContextOp(ctx, xq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{xaddress.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (xq *XAddressQuery) FirstX(ctx context.Context) *XAddress {
	node, err := xq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first XAddress ID from the query.
// Returns a *NotFoundError when no XAddress ID was found.
func (xq *XAddressQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = xq.Limit(1).IDs(setContextOp(ctx, xq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{xaddress.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (xq *XAddressQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := xq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single XAddress entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one XAddress entity is found.
// Returns a *NotFoundError when no XAddress entities are found.
func (xq *XAddressQuery) Only(ctx context.Context) (*XAddress, error) {
	nodes, err := xq.Limit(2).All(setContextOp(ctx, xq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{xaddress.Label}
	default:
		return nil, &NotSingularError{xaddress.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (xq *XAddressQuery) OnlyX(ctx context.Context) *XAddress {
	node, err := xq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only XAddress ID in the query.
// Returns a *NotSingularError when more than one XAddress ID is found.
// Returns a *NotFoundError when no entities are found.
func (xq *XAddressQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = xq.Limit(2).IDs(setContextOp(ctx, xq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{xaddress.Label}
	default:
		err = &NotSingularError{xaddress.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (xq *XAddressQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := xq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of XAddresses.
func (xq *XAddressQuery) All(ctx context.Context) ([]*XAddress, error) {
	ctx = setContextOp(ctx, xq.ctx, ent.OpQueryAll)
	if err := xq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*XAddress, *XAddressQuery]()
	return withInterceptors[[]*XAddress](ctx, xq, qr, xq.inters)
}

// AllX is like All, but panics if an error occurs.
func (xq *XAddressQuery) AllX(ctx context.Context) []*XAddress {
	nodes, err := xq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of XAddress IDs.
func (xq *XAddressQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if xq.ctx.Unique == nil && xq.path != nil {
		xq.Unique(true)
	}
	ctx = setContextOp(ctx, xq.ctx, ent.OpQueryIDs)
	if err = xq.Select(xaddress.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (xq *XAddressQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := xq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (xq *XAddressQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, xq.ctx, ent.OpQueryCount)
	if err := xq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, xq, querierCount[*XAddressQuery](), xq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (xq *XAddressQuery) CountX(ctx context.Context) int {
	count, err := xq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (xq *XAddressQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, xq.ctx, ent.OpQueryExist)
	switch _, err := xq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (xq *XAddressQuery) ExistX(ctx context.Context) bool {
	exist, err := xq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the XAddressQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (xq *XAddressQuery) Clone() *XAddressQuery {
	if xq == nil {
		return nil
	}
	return &XAddressQuery{
		config:     xq.config,
		ctx:        xq.ctx.Clone(),
		order:      append([]xaddress.OrderOption{}, xq.order...),
		inters:     append([]Interceptor{}, xq.inters...),
		predicates: append([]predicate.XAddress{}, xq.predicates...),
		// clone intermediate query.
		sql:  xq.sql.Clone(),
		path: xq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.XAddress.Query().
//		GroupBy(xaddress.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (xq *XAddressQuery) GroupBy(field string, fields ...string) *XAddressGroupBy {
	xq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &XAddressGroupBy{build: xq}
	grbuild.flds = &xq.ctx.Fields
	grbuild.label = xaddress.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.XAddress.Query().
//		Select(xaddress.FieldCreatedAt).
//		Scan(ctx, &v)
func (xq *XAddressQuery) Select(fields ...string) *XAddressSelect {
	xq.ctx.Fields = append(xq.ctx.Fields, fields...)
	sbuild := &XAddressSelect{XAddressQuery: xq}
	sbuild.label = xaddress.Label
	sbuild.flds, sbuild.scan = &xq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a XAddressSelect configured with the given aggregations.
func (xq *XAddressQuery) Aggregate(fns ...AggregateFunc) *XAddressSelect {
	return xq.Select().Aggregate(fns...)
}

func (xq *XAddressQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range xq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, xq); err != nil {
				return err
			}
		}
	}
	for _, f := range xq.ctx.Fields {
		if !xaddress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if xq.path != nil {
		prev, err := xq.path(ctx)
		if err != nil {
			return err
		}
		xq.sql = prev
	}
	return nil
}

func (xq *XAddressQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*XAddress, error) {
	var (
		nodes = []*XAddress{}
		_spec = xq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*XAddress).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &XAddress{config: xq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, xq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (xq *XAddressQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := xq.querySpec()
	_spec.Node.Columns = xq.ctx.Fields
	if len(xq.ctx.Fields) > 0 {
		_spec.Unique = xq.ctx.Unique != nil && *xq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, xq.driver, _spec)
}

func (xq *XAddressQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(xaddress.Table, xaddress.Columns, sqlgraph.NewFieldSpec(xaddress.FieldID, field.TypeUint64))
	_spec.From = xq.sql
	if unique := xq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if xq.path != nil {
		_spec.Unique = true
	}
	if fields := xq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, xaddress.FieldID)
		for i := range fields {
			if fields[i] != xaddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := xq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := xq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := xq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := xq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (xq *XAddressQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(xq.driver.Dialect())
	t1 := builder.Table(xaddress.Table)
	columns := xq.ctx.Fields
	if len(columns) == 0 {
		columns = xaddress.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if xq.sql != nil {
		selector = xq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if xq.ctx.Unique != nil && *xq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range xq.predicates {
		p(selector)
	}
	for _, p := range xq.order {
		p(selector)
	}
	if offset := xq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := xq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// XAddressGroupBy is the group-by builder for XAddress entities.
type XAddressGroupBy struct {
	selector
	build *XAddressQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (xgb *XAddressGroupBy) Aggregate(fns ...AggregateFunc) *XAddressGroupBy {
	xgb.fns = append(xgb.fns, fns...)
	return xgb
}

// Scan applies the selector query and scans the result into the given value.
func (xgb *XAddressGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, xgb.build.ctx, ent.OpQueryGroupBy)
	if err := xgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*XAddressQuery, *XAddressGroupBy](ctx, xgb.build, xgb, xgb.build.inters, v)
}

func (xgb *XAddressGroupBy) sqlScan(ctx context.Context, root *XAddressQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(xgb.fns))
	for _, fn := range xgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*xgb.flds)+len(xgb.fns))
		for _, f := range *xgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*xgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := xgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// XAddressSelect is the builder for selecting fields of XAddress entities.
type XAddressSelect struct {
	*XAddressQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (xs *XAddressSelect) Aggregate(fns ...AggregateFunc) *XAddressSelect {
	xs.fns = append(xs.fns, fns...)
	return xs
}

// Scan applies the selector query and scans the result into the given value.
func (xs *XAddressSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, xs.ctx, ent.OpQuerySelect)
	if err := xs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*XAddressQuery, *XAddressSelect](ctx, xs.XAddressQuery, xs, xs.inters, v)
}

func (xs *XAddressSelect) sqlScan(ctx context.Context, root *XAddressQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(xs.fns))
	for _, fn := range xs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*xs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := xs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
